### PR TITLE
Do not require sudo

### PR DESCRIPTION
**Pull request by achanda**
Enables travis builds on containers. Faster.

### CODE REVIEW

**Comment by shailesh1729** [comment]
I had a Rust 1.2 Beta on my laptop. When trying to compile SciRust with it, I found following errors. 

src\lib.rs:28:2: 28:19 error: #[feature] may not be used on the beta release channel
src\lib.rs:28  #![feature(core)]
               ^~~~~~~~~~~~~~~~~
src\lib.rs:29:1: 29:19 error: #[feature] may not be used on the beta release channel
src\lib.rs:29 #![feature(alloc)]
              ^~~~~~~~~~~~~~~~~~
src\lib.rs:30:1: 30:21 error: #[feature] may not be used on the beta release channel
src\lib.rs:30 #![feature(step_by)]
              ^~~~~~~~~~~~~~~~~~~~
src\lib.rs:31:1: 31:21 error: #[feature] may not be used on the beta release channel
src\lib.rs:31 #![feature(convert)]
              ^~~~~~~~~~~~~~~~~~~~
src\lib.rs:32:1: 32:18 error: #[feature] may not be used on the beta release channel
src\lib.rs:32 #![feature(test)]
              ^~~~~~~~~~~~~~~~~
error: aborting due to 5 previous errors
Could not compile `scirust`.

I am somewhat confused in the differences between the nightly channel and the beta/stable channel. I am wondering what all conventions should I follow to make the code  work on both channels? Or should I stick only to the nightly channels?  Also, is it possible to define two different build configurations in travis.yaml to allow building both on latest nightly and the latest stable releases?

**Comment by achanda** [comment]
The nightly channel is bleeding edge code, this means some features might be unstable because they are not vetted by the community. If people do not like a new API in nightly, it might be removed. The beta channel is more stable. Thus, not all nightly features can be used in beta. It seems scirust is using some unstable nightly features, which makes the compiler complain in beta. The way to make scirust compile on both beta and nightly is to not use unstable fetaures. However, that might not be possible always. Please take this with a grain of salt, this is totally my understanding and I'm a beginner in Rust :)
Travis can do builds on multiple channels, I can get this done.

**Comment by daniel-vainsencher** [comment]
I suggest to build in all channels (because information is good), and take
as serious only complaints from unstable. In my opinion, there will keep
being valuable in unstable for a while, and scirust is not ready to commit
to an API anyway, so why worry about stabler channels?

On Tue, Aug 4, 2015 at 12:21 PM, Abhishek Chanda <notifications@github.com>
wrote:

> The nightly channel is bleeding edge code, this means some features might
> be unstable because they are not vetted by the community. If people do not
> like a new API in nightly, it might be removed. The beta channel is more
> stable. Thus, not all nightly features can be used in beta. It seems
> scirust is using some unstable nightly features, which makes the compiler
> complain in beta. The way to make scirust compile on both beta and nightly
> is to not use unstable fetaures. However, that might not be possible
> always. Please take this with a grain of salt, this is totally my
> understanding and I'm a beginner in Rust :)
> Travis can do builds on multiple channels, I can get this done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indigits/scirust/pull/14#issuecomment-127663977>.
>



-- 
Daniel Vainsencher

**Comment by shailesh1729** [comment]
Daniel

As of today we have some feature gates  added. Due to them the code simply
doesn't build on beta channel. It's not worth it building on it. Hopefully
by end of year these feature gates won't be required as they will become
part of standard Rust.

It's actually important to have the "BUILD: PASSING" ticker on the
rust-ci,org.  A failing build would put off people from looking at the
library.

With regards,

- Shailesh

**Comment by daniel-vainsencher** [comment]
That's also an important consideration, I agree.

On Wed, Aug 5, 2015 at 4:09 AM, Shailesh Kumar <notifications@github.com>
wrote:

> Daniel
>
> As of today we have some feature gates added. Due to them the code simply
> doesn't build on beta channel. It's not worth it building on it. Hopefully
> by end of year these feature gates won't be required as they will become
> part of standard Rust.
>
> It's actually important to have the "BUILD: PASSING" ticker on the
> rust-ci,org. A failing build would put off people from looking at the
> library.
>
> With regards,
>
> - Shailesh
>
>
>
>
> On Aug 5, 2015 12:47 AM, "Daniel Vainsencher" <notifications@github.com>
> wrote:
>
> > I suggest to build in all channels (because information is good), and
> take
> > as serious only complaints from unstable. In my opinion, there will keep
> > being valuable in unstable for a while, and scirust is not ready to
> commit
> > to an API anyway, so why worry about stabler channels?
> >
> > On Tue, Aug 4, 2015 at 12:21 PM, Abhishek Chanda <
> notifications@github.com
> > >
> > wrote:
> >
> > > The nightly channel is bleeding edge code, this means some features
> might
> > > be unstable because they are not vetted by the community. If people do
> > not
> > > like a new API in nightly, it might be removed. The beta channel is
> more
> > > stable. Thus, not all nightly features can be used in beta. It seems
> > > scirust is using some unstable nightly features, which makes the
> compiler
> > > complain in beta. The way to make scirust compile on both beta and
> > nightly
> > > is to not use unstable fetaures. However, that might not be possible
> > > always. Please take this with a grain of salt, this is totally my
> > > understanding and I'm a beginner in Rust :)
> > > Travis can do builds on multiple channels, I can get this done.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/indigits/scirust/pull/14#issuecomment-127663977>.
> > >
> >
> >
> >
> > --
> > Daniel Vainsencher
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/indigits/scirust/pull/14#issuecomment-127726555>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indigits/scirust/pull/14#issuecomment-127908503>.
>



-- 
Daniel Vainsencher

**Comment by shailesh1729** [comment]
Have setup a Google group https://groups.google.com/forum/#!forum/scirust
 for announcements and general discussions about the library design and
other topics which are not issue specific and probably open ended
discussions.

On Wed, Aug 5, 2015 at 9:46 PM, Daniel Vainsencher <notifications@github.com

**Pull request merged**
