### PR TITLE
[MRG?] Access matrices through iterators where possible: the case of the major diagonal.

### PR DESCRIPTION
**Pull request by daniel-vainsencher**
Not ready for merge. Started from changing implementation of trace to use uniform access to the diagonal elements. Current plan is:
- Separate the access loop into its own function. 
- Put the function interface into a trait function. The "Shape" trait seems like the right place.
- Move trace functionality into a trait... maybe NumberMatrix?

If this sounds ok, I'll do those, then generalize to other functionality.

### CODE REVIEW

**Comment by daniel-vainsencher** [comment]
Ok, now I'm confused. Added the feature that is supposed to be required, still doesn't work. Ideas what is really wrong welcome.

**Comment by shailesh1729** [comment]
Will see today. Apologize for delay.

**Comment by shailesh1729** [comment]
I don't see the DiagIter being used in trace method yet.

 I thought further about the iterator approach. I have few concerns about it.  The changes in trace() itself look okay where u replaced calculation using stride with step which is stride + 1.

- Creating an iterator has it's own overhead of storage cost, construction time cost. This may not be significant for large matrices, but would be important for small matrices. Though this is not a big concern. 
- Is Rust fully able to rewrite a next() method call overhead and unwrapping of Option<> return type overhead into a standard optimized for loop? It does claim so. But I haven't verified it myself. 
- In the next() method you have written ``let offset = self.pos * (self.stride + 1);`` Now this involves an extra multiplication instruction. My original implementation has a simple addition operation. In general, multiplication is considered more costly operation than addition. 
- You also ended up calling ``.clone()`` in next implementation. Rust actually makes it a bit hard to write low level generic code. 
- A typical optimization technique involves unrolling a loop and executive multiple instructions in parallel (for example by using MMX instructions). Doing such a thing is straightforward if we are working with standard C style loops. I am not very sure if Iterators can be optimized in that fashion.

**Comment by daniel-vainsencher** [comment]
Hi Shailesh!

This conversation is fun :)
- This is Work In Progress [WIP]. I am trying to make the changes very gradually, to learn as I go, to give both of us opportunities to think about issues as you mention, and to keep the feedback from rustc manageable. In particular, first I cleaned the trace, then I added the iterator, next I will make the trace use the iterator. So, that part is coming soon.
- About iterator efficiency: rustc is moving in the direction of replacing other constructs (from_fn was removed, for example) by iterators; I think the goal is to use iterators all over the place, as a zero cost abstraction, as loops are in C. In particular, using iterators is one of the ways that Rust accepts for avoiding array bounds checks: make sure that the iterator cannot access the wrong data when setting it up, then you don't need to test every access. I think this is a smart approach to the problem! I haven't tried to test this myself, but a dot product I implemented using an iterator had equal or better performance than the one used by numpy (pretty well optimized C). So this seems reasonably a safe bet, though appropriate performance tests would probably be a good idea.
- Iterator construction/storage costs: Iterators are generally 1-3 fields, allocated on the stack, so the cost is minimal, and highly accessible to LLVM for further optimization. So indeed, I think we can reasonably ignore the storage and construction costs, even for small matrices.
- let offset = self.pos * (self.stride + 1): you are right! thanks for reminding me. I've fixed it on my machine, will include in the PR in the next push (working on something else at the moment). I am not sure whether an integer multiply vs add makes a difference in a data-intensive code like this (probably memory bandwidth bound anyway). The question of how to monitor performance (and get alerted on regressions) in this kind of project is becoming pretty interesting...
- About clone and writing low level generic code: yes, I didn't particular try to get the best possible performance out of trace, in particular if clone worked for you I wasn't going to change it. But my experience [1] with the dot product was pretty amazing. The language feature are there, and while the documentation is still lacking, the community is very much willing to help. There in the end people suggested multiple excellent solutions. I guess the clone can be removed by using an iterator that is generic over references or not. Of course when f64 is not much bigger than a pointer, it is not clear that the clone costs us anything.
- About SIMD instructions and parallelizing a loop: I am not sure this is not applicable at all to trace: IIUC, SIMD instructions operate on contiguous memory. In rust, this corresponds to slices. Hence I think the highest levels of efficiency can be reached only when operating on slices. Nicely, given something that is a slice (e.g., row in a row major matrix), we can get the iterator for it. Therefore, operators defined over an iterator will also work on a slice. Because the genericity comes from code generation, not indirection, the generated code can use the memory locality (don't know whether it does in practice). In rustc, SIMD is currently unstable and manual. I guess it will become automatic and stable at some point, so not sure it is worth chasing right now. What are some good examples of matrix algorithms where you want to have the option to parallelize them, and an iterator based implementation could get in the way? maybe that is the highest risk issue that we better check out soon.

[1] https://www.reddit.com/r/rust/comments/3f7hd9/fighting_the_borrow_checker_for_generic_dot/

**Comment by shailesh1729** [comment]
Here are some matrix operations in scirust which are heavily dependent on locality of reference and can potentially be further accelerated via SIMD etc.  in future: 

- matrix multiplication  A * B  ( can be found in matrix_transpose.rs)
- gram matrix computation :  A' * A.  [ A standard part of a normal equation (A' A) x = A' b which is used for solving least squares problems. 
- Gaussian elimination ( GaussElimination structure and its solve method in linalg/linear_system.rs) 

In fact I have two implementations of matrix multiplication.  In my design, matrices are column major following MATLAB/FORTRAN convention. A naive matrix multiplication  tries to multiply each row of A with each column of B resulting in extremely slow performance for large matrices as there are too many cache misses.  The alternative uses a cache oblivious algorithm to compute the transpose of A first and then multiplies each column of A' with each column of B to achieve A * B. 

Approach 1 is implemented in ``multiply_simple`` function.
Approach 2 is implemented as a combination of 
``
                    let m2 = m.transpose();
                    // Matrix multiplication with transpose
                    multiply_transpose_simple(&m2, &m).is_ok();
``

Benchmarking showed the second approach to be  markedly better than the first one for large matrices. 

Looks like I forgot to integrate the second approach in the implementation of ``ops::Mul`` trait. My bad.

**Comment by shailesh1729** [comment]
BTW, I don't think f32 and f64 will be the only number types used for representing real matrices. I plan to introduce Fixed point data types also.  So a QM.N [1] format would give full flexibility to the user of the library to choose how many bits they need to represent the integer part and how many bits for the fractional part while keeping the data type within say 16 bits or 32 bits.  There are many signal processing applications where this scheme would work just fine and won't need the full dynamic range of floating point numbers.  This also allows us to pack more data in less memory. Assuming that Rust would someday grow into embedded domains, having this flexibility would allow this generic library to be used in very low memory applications too.

I believe that well designed scientific computing algorithms are expected to be CPU bound rather than data bound. See [2] for some discussion. I am not an expert though. 

[1] https://en.wikipedia.org/wiki/Q_(number_format)
[2] http://www.quora.com/What-are-some-examples-of-CPU-bound-and-non-CPU-bound-problems-What-would-be-the-best-programming-language-to-tackle-each-situation

**Comment by daniel-vainsencher** [comment]
Yes, I'm doing machine learning algorithms, specifically first order stochastic optimization. This consists mostly of matrix vector products, which as Victor says, is memory bandwidth bound. In this case, the most important thing is efficient memory access, a stray in-register instruction doesn't matter. I believe the same holds for reasonable implementations of trace.

For smaller representations, my point stands even more strongly: manipulating their copies is generally cheaper than manipulating pointers to them (so clone is not more expensive than using references). For, say, BigInts, avoiding copies begins to matter. 

BTW, is there a reason to use only column major format? One of my goals is to support interoperation with NumPy, which is row major by default.

**Comment by daniel-vainsencher** [comment]
Seems like putting most functionality on traits should make it easy to also support row major representation. I wonder if that is a zero copy way to implement transpose.

**Comment by daniel-vainsencher** [comment]
Interesting that the matrix multiplication algorithm you mention is cache oblivious, I didn't know that. It also seems to reduce matrix multiplication to lots of slice-slice dot products, which is nice. That seems perfectly well suited for building on top of efficient iterators for slices. If SIMD doesn't work with iterators, then we can write a dot product that does SIMD, then build the MMM and gram matrix calculation on top of those instead. In both cases, unsafe access patterns can be hidden a couple of layers under.

**Comment by shailesh1729** [comment]
A useful place for applying your diagonal iterator : has_zero_on_diagonal in singularity.rs.

**Comment by shailesh1729** [comment]
I have just committed some changes. ```Shape``` now has ```get()``` and ```get_unchecked()``` as separate methods. ```get()``` now returns ```Option<T>``` .  ```get_unchecked()``` is ```unsafe```.  All parts of code have been updated accordingly and unit tests are running fine. You can review the changes.  Two of your changes in ```ops.rs``` and ```trace``` method got anyway incorporated as I was trying to compile with the new rust nightly and  ```trace``` method was affected by the changes related to ```get()```. 

You will need to merge it before you can push your changes. 

Now, many parts of the code (especially in linear algebra section) are littered with the usage of ```get_unchecked()``` thus having ```unsafe``` blocks in their implementations. They are pretty good use cases of experimenting with different kinds of iterators on the matrix data. Good iterators are likely to reduce the use of ```get_unchecked()``` as much as possible.

**Comment by daniel-vainsencher** [comment]
Cool!

**Comment by daniel-vainsencher** [comment]
Ok, so diag_iterator is now public, and along with the row and column iterators, requires little of T (actually, I don't understand why most of the bounds that remain are still necessary, but the compiler is demanding them.) Might be ready to merge.

**Comment by daniel-vainsencher** [comment]
I think I'm done with the diagonal access case. If it looks good to you, lets merge it and then work on replacing other instances of get_unchecked with iterators separately.

**Comment by shailesh1729** [comment]
The code looks good to me.  As expected the new code is shorter and more expressive and easier to maintain.

Few comments: 

I had put ```+#![feature(associated_type_defaults)]``` in ```lib.rs```. I guess this need not be put in ```ops.rs``` additionally. 

Would it be possible for you to write a couple of test benches for say ```trace()```  and ```diagonal_vector``` so that we can verify that we are not really losing anything on performance? 

You could go like this:
a) clone separately from scriust.
b) develop some simple benchmarks and run them.  Preferably for large matrix sizes (2048x2048).   
c) Store the performance numbers in some sheet.
d) Copy the benchmarks to your new code.
e) Run and generate the numbers again.
f) Checkin the benchmarks also as part of this pull requests.
g) Publish before and after optimization numbers here. 

This will help in having a strong justification for introducing the changes.

**Comment by daniel-vainsencher** [comment]
I'm not sure trace etc. are the most important topics for a benchmark, but sure. I like the approach in [1], are we ok with adding Criterion as a dependency? If we're going to heat up the world to get data, might as well make the most of it. Ideally, this should be run from CI, with graphs published over time, regressions warned about etc. But I don't know of an easy way to automate this stuff.

[1] https://github.com/danburkert/rust-ringbuf/blob/master/src/bin/bench.rs

**Comment by shailesh1729** [comment]
I don't see criterion yet on crates.io.  It is a port of a corresponding Haskell library. I guess you already have experience with Haskell. So my question would be, your comfort level with the library, what is it's stability level? Is API expected to change frequently? Initially I had some dependencies with different rust libraries directly from GITHUB.  After crates.io was launched, I slowly restricted myself to more popular and stable libraries there and removed other dependencies.

**Comment by daniel-vainsencher** [comment]
I have some experience with haskell, used criterion just a little bit. I
have good experience with profiling, but my experience with benchmarking is
all semi automated, and then it never gets run often enough to help etc. I
only just saw criterion for rust, so have no real information about those
questions. My guess is that the API will be relatively stable simply
because it is a port of something well-established, but it is only a guess.
Maybe worth waiting for a crates.io version.

On Tue, Aug 4, 2015 at 2:40 PM, Shailesh Kumar <notifications@github.com>
wrote:

> I don't see criterion yet on crates.io. It is a port of a corresponding
> Haskell library. I guess you already have experience with Haskell. So my
> question would be, your comfort level with the library, what is it's
> stability level? Is API expected to change frequently? Initially I had some
> dependencies with different rust libraries directly from GITHUB. After
> crates.io was launched, I slowly restricted myself to more popular and
> stable libraries there and removed other dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indigits/scirust/pull/16#issuecomment-127707438>.
>



-- 
Daniel Vainsencher

**Pull request merged**
