### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by achanda**

### CODE REVIEW

**Comment by achanda** [comment]
@shailesh1729 this seems to be building with stable. Any idea why? The `.travis.yml` file says `nightly`

**Comment by shailesh1729** [comment]
I haven't checked for 3-4 weeks. Earlier, some of the features were not
working with the Rust Beta release. Hence, I had to use the nightly builds.
  Are you interested in contributing more?

**Comment by achanda** [comment]
Sure, I can take a look whenever I can.

**Comment by shailesh1729** [comment]
My skype id is shailesh.kumar.in  . Let's chat some time.

**Comment by achanda** [comment]
@shailesh1729 will do.
This patch fixes the build and all tests pass. You want to merge it now?

**Comment by shailesh1729** [comment]
I will.

**Comment by shailesh1729** [comment]
It's done.

**Comment by shailesh1729** [comment]
Thanks a lot for the help :) The structure of the library is still
evolving. I want it to be strongly grounded in fundamental math concepts
and take as much advantage of the Rust generics as possible. Not sure where
this effort will reach. But hopefully something good will come out of it.

**Comment by achanda** [comment]
Thanks. The library looks great so far :)
Now that the build is fixed again, you should bump the version and push a new version to crates.io.

**Comment by shailesh1729** [comment]
Done.  The new version is up on crates.io.

**Comment by shailesh1729** [comment]
For some unknown reason, the documentation on http://www.rust-ci.org/ never
gets updated.  I tried many things but it's probably some bug in the
integration between travis build system and the rust-ci.org  integration.
If you can identify any issue with the way my .travis.yml file is written,
do let me know.  crates.io points to the same documentation link and it is
old!

**Comment by achanda** [comment]
@shailesh1729 I did not see anything that I thought was wrong. Might just be a bug, as you said. I did notice that a lot of people publish docs on their own websites or github pages. You can do that maybe?

**Comment by shailesh1729** [comment]
That is already in place (through the separate gh-pages branch concept).
But it's not really automated, in the sense that it doesn't get updated
with every Travis successful build. And I am lazy to regularly update it :)
 Will see what best can be done.  Thanks.

**Pull request merged**
